# cat environments/minikube/dev/applications/sealed-secrets/sealed-secrets-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  interval: 5m
  chart:
    spec:
      chart: sealed-secrets
      version: '2.5.2'
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: sealed-secrets
      interval: 5m
  dependsOn: [] # link to other HelmReleases that must be deployed before this one

  # parameters for the different helm lifecycle operations :
  install: {}
  upgrade: {}
  test: {}
  rollback: {}
  uninstall: {}

  # parameters for the helm installation / upgrade :
  values: {} # map of values to use for the helm install
  valuesFrom: [] # list of resources to use to populates the values (e.g. secrets)
  postRenderers: []

  suspend: false # disable the Helm reconciliation - useful when you're testing deployments manually.

